package com.mkdev.mkboardgames.challenges

/**
 * The challenge names are kept separately from the board positions so the
 * catalogue can be edited from the design brief without changing validation
 * data or progress keys.
 */
object ChessChallengeCatalogue {
    private val titles = listOf(
        "Mate in 1 (Back-Rank)",
        "Mate in 1 (Scholar's Mate pattern)",
        "The Simple Fork",
        "Winning a Free Piece",
        "Back-Rank Weakness",
        "Simple Pin",
        "Simple Skewer",
        "Removing the Defender",
        "Simple Double Attack",
        "Discovered Attack",
        "Mate in 2 (Smothered Mate setup)",
        "Pawn Promotion Race",
        "Trapped Piece",
        "Overloaded Defender",
        "Simple X-Ray Attack",
        "Intermediate Fork (Queen)",
        "Defensive Interposition",
        "Simple Clearance Sacrifice",
        "Breaking the King's Pawn Shield",
        "Basic Deflection",
        "Interception",
        "Seventh-Rank Rook Incursion",
        "Centralizing the Knight",
        "Simple Counter-Check",
        "Opposition Basics",
        "The Greek Gift Sacrifice (Bxh7+)",
        "Advanced Pin and Win",
        "Intermediate Skewer",
        "Deflection of the Guard",
        "Zwischenzug (Intermediate Move)",
        "Underpromotion Tactician",
        "The Windmill Tactic",
        "Boden's Mate",
        "Anastasia's Mate",
        "Arabian Mate",
        "Smothered Mate (Classic)",
        "Trapped Queen Maneuver",
        "Interference Combination",
        "Perpetual Check Defense",
        "Active King Endgame",
        "The Desperado",
        "Rook Lift (File Transfer)",
        "Blockade and Counter",
        "Pawn Storm Breakthrough",
        "The Trapped Rook",
        "Minor Piece Harmony",
        "Hanging Pawns Vulnerability",
        "The Hook Mate",
        "Clearance via Sacrifice",
        "Zugzwang Recognition",
        "Multi-Piece Sacrifice Attack",
        "The Defensive Fortress",
        "Positional Exchange Sacrifice",
        "Deep Discovered Attack Chain",
        "The Triangulation Maneuver",
        "Reti's Endgame Study",
        "Queen Sacrifice for Position",
        "The Long Skewer",
        "Counter-Attack Intermezzo",
        "Complex Pawn Breakthrough",
        "Knight Outpost Domination",
        "The Lucena Position",
        "The Philidor Position",
        "Elimination of Counterplay",
        "The Woptimize Attack",
        "Overloading the Bishop Pair",
        "Deflecting the King",
        "The Rook Rampage",
        "Exploiting Color Complex Weaknesses",
        "The Stalemate Trap Defense",
        "Advanced Intermediate Move (Zwischenzug) in Endgames",
        "The Opposition Breakthrough",
        "Blocking the Breakthrough",
        "The Clearance Diagonal",
        "Systematic Pawn Minorities",
        "The Grandmaster Quiet Move",
        "Aesthetic Queen Sacrifice (Mikhail Tal Style)",
        "The Perpetual Pursuit",
        "Deep Study: The Under-Promoting Rook Saver",
        "The Berserk Rook Sacrifice",
        "Prophylactic Masterclass",
        "The Zugzwang Masterwork",
        "Brilliant Knight Tour",
        "The Double-Edge Counter-Sacrifice",
        "Opposition Matrix in Complex Endgames",
        "The Smothered Masterpiece",
        "Defending the Impossible",
        "The Windmill Grand-Combo",
        "Positional King Walk",
        "The Invisible Intermezzo",
        "The Bishop and Knight Mate Execution",
        "Artistic Rook and Pawn Study",
        "The Decoy Queen Tour",
        "The Grandmaster Fortress Destruction",
        "The Ultimate Desperado Sequence",
        "Deep Calculation King Hunt",
        "The Silent Interception",
        "Master-Level Under-Promotion Net",
        "The Zenith Combination",
        "The Grandmaster Immortal Test",
    )

    val size: Int
        get() = titles.size

    fun titleFor(level: Int): String = titles.getOrNull(level - 1) ?: "Chess challenge"
}